### ISSUE TITLE
Backend: Implement POST /campaigns/{campID}/ads

### ISSUE THREAD

**Issue by sjfoz1019** [bkehle/307backend#39]
**User Story:** As a user, I would like to create a new ad associated with a specific campaign.

## Acceptance Criteria:
- [x] Retrieve a campaign by id from the backend database
- [x] Create a new ad from JSON input
- [x] Add new add to backend database
- [x] Return URL in Location header
- [x] Have REST API endpoint accessible
    - [ ] Passes Postman test suite

**Time Estimate:** 2 hours

**Comment by sjfoz1019** [comment]
**Bug:** Ad is added to campaign, but not shown when getting campaign/ads later
**Cause:** Updated campaign not saved to database, old data returned upon GET request

**Update:** Added `campaignRepo.save(camp)` after `camp.addAd(ad)`, get error `Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find com.csc.adbackend.Ad with id 0; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.csc.adbackend.Ad with id 0] with root cause`

**Update:** Fixed! Changed Ad annotation from @ Entity to @ Embeddable and removed @ Id annotation.
Biggest help: https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/embedded-element-collection.html

**Time Sunk:** 1 hour

**Comment by sjfoz1019** [comment]
**TODO:** Needs correct error handling

**Update:**
- Implemented checking for missing values on POST /campaigns and returning correct errors
- Can't implement badValue checking since Spring handles JSON parsing and jackson throws `com.fasterxml.jackson.databind.exc.MismatchedInputException` before we get control of the method

**Time Spent:** 30 minutes

**Comment by sjfoz1019** [comment]
**Total Billed Time:** 1.5 hours
